#ifndef __PADDLEVINO_MAIN_H__
#define __PADDLEVINO_MAIN_H__

// CLI usage/help text for the paddlevino executable.
// Long-flag, JSON-friendly interface. See README.md for full documentation.

static const char *usageMsg =
    "paddlevino --input <file|dir> [options]\n";

static const char *examplesMsg =
    "Examples:\n"
    "  paddlevino.exe --input imagen.png --engine openvino --output resultado.json\n"
    "  paddlevino.exe --input carpeta\\ --recursive --format json\n"
    "  paddlevino --input photo.jpg --format txt\n";

static const char *requiredMsg =
    "  --input <path>        Image file or a directory of images (required)\n";

static const char *optionalMsg =
    "  --recursive            When --input is a directory, search it recursively\n"
    "  --output <path>        Write results to this file instead of stdout\n"
    "  --format json|txt|reading  Output format (default: json)\n"
    "                         json:    full detail (text, confidence, boxes)\n"
    "                         txt:     one detected text run per line, with confidence\n"
    "                         reading: first line is the average confidence, then\n"
    "                                  clean text re-flowed into reading order (text\n"
    "                                  runs on the same physical line are merged),\n"
    "                                  no boxes or per-line labels\n"
    "  --engine cpu|openvino  Execution backend (default: cpu)\n"
    "  --models-dir <dir>     Directory containing the model files (default: models)\n"
    "  --det <file>           Detection model file name (default: det.onnx)\n"
    "  --cls <file>           Angle classification model file name (default: cls.onnx)\n"
    "  --rec <file>           Recognition model file name (default: rec.onnx)\n"
    "  --keys <file>          Character dictionary file name (default: ppocrv6_dict.txt)\n"
    "  --threads <int>        ONNX Runtime thread count (default: 4)\n"
    "  --padding <int>        Border padding added to input images (default: 50)\n"
    "  --max-side-len <int>   Resize long side to this value, 0 = no resize (default: 1024)\n"
    "  --box-score-thresh <f> Detection box score threshold (default: 0.5)\n"
    "  --box-thresh <f>       Detection binarization threshold (default: 0.3)\n"
    "  --unclip-ratio <f>     Detection box expansion ratio (default: 1.6)\n"
    "  --no-angle             Disable the angle classification model\n"
    "  --no-most-angle        Disable \"most probable angle\" voting\n"
    "  --reading-row-overlap <f>  --format reading row-clustering threshold:\n"
    "                         minimum vertical-span IoU for two text runs to be\n"
    "                         merged onto the same output line. Raise it (e.g.\n"
    "                         0.6-0.7) if unrelated lines are getting merged;\n"
    "                         lower it (e.g. 0.3-0.4) if runs on the same line\n"
    "                         (common with small/dense text) are staying split\n"
    "                         (default: 0.5)\n"
    "\n"
    "  Cell structure detection (all off by default):\n"
    "  --detect-cells         Detect field/table cells by morphology, report them\n"
    "                         under the JSON \"cells\" key, and use them to group\n"
    "                         text in --format reading. Consider lowering\n"
    "                         --reading-row-overlap to ~0.25 when using this\n"
    "  --reading-column-gap <f>  Horizontal gap, in line heights, above which two\n"
    "                         runs are separated by \"|\" instead of a space in\n"
    "                         --format reading. Only applies once --detect-cells\n"
    "                         restructures the output (default: 0.8)\n"
    "  --cell-h-frac <int>    Horizontal kernel divisor (width/N). This is the\n"
    "                         filter that keeps false positives at zero on plain\n"
    "                         text; lowering it relaxes that (default: 28)\n"
    "  --cell-v-frac <int>    Vertical kernel divisor (height/N). The most\n"
    "                         sensitive one: raise it if short field boxes are\n"
    "                         being missed (default: 80)\n"
    "  --cell-min-width <f>   Minimum cell width as a fraction of the page width\n"
    "                         (default: 0.012)\n"
    "  --cell-min-height <f>  Minimum cell height as a fraction of the page height\n"
    "                         (default: 0.006)\n"
    "  --cell-max-area <f>    Maximum cell area as a fraction of the page; drops\n"
    "                         section frames (default: 0.6)\n"
    "  --cell-rectangularity <f>  Minimum contourArea/boundingBoxArea (default: 0.7)\n"
    "\n"
    "  Checkbox detection (all off by default):\n"
    "  --detect-checkboxes    Detect checkboxes and whether they are ticked\n"
    "  --checkbox-model <file>  Model file name inside --models-dir\n"
    "                         (default: checkbox.onnx)\n"
    "  --checkbox-profile strict|balanced|aggressive  Preset for the knobs below.\n"
    "                         strict: no rescue, conf 0.35, form-min 5.\n"
    "                         balanced: the defaults listed here.\n"
    "                         aggressive: conf 0.15, rescue-conf 0.03,\n"
    "                         rescue-min-cluster 1. Any explicit flag overrides\n"
    "                         the profile (default: balanced)\n"
    "  --checkbox-conf <f>    Confidence threshold of the main pass (default: 0.25)\n"
    "  --checkbox-iou <f>     NMS IoU, crossing classes (default: 0.45)\n"
    "  --checkbox-max-saturation <f>  Maximum mean HSV saturation; drops colour\n"
    "                         logos. Measured: boxes 0-0.07, logo 90-134\n"
    "                         (default: 20.0)\n"
    "  --checkbox-input-size <int>  Model input side, letterboxed (default: 1024)\n"
    "  --checkbox-form-min <int>  Boxes the conservative pass must find for the\n"
    "                         document to count as a form and enable the rescue.\n"
    "                         Raising it is more conservative, 0 disables the gate\n"
    "                         (default: 3)\n"
    "  --no-checkbox-rescue   Disable the low-confidence rescue entirely\n"
    "  --checkbox-rescue-conf <f>  Minimum confidence of a rescue candidate\n"
    "                         (default: 0.04)\n"
    "  --checkbox-rescue-min-cluster <int>  Candidates aligned in the same X\n"
    "                         column needed to accept them (default: 2)\n"
    "  --checkbox-rescue-x-tol <f>  Pixel tolerance for grouping candidates into\n"
    "                         a column (default: 20.0)\n"
    "  --checkbox-rescue-spacing-tol <f>  Row-spacing tolerance, as a multiple of\n"
    "                         the median gap, when pruning strays (default: 1.6)\n"
    "  --checkbox-dedup-y-frac <f>  Y distance (fraction of box height) below\n"
    "                         which two detections are the same object\n"
    "                         (default: 0.6)\n"
    "  --no-checkbox-snap     Use the raw network box without snapping it to the\n"
    "                         real rectangle (escape hatch)\n"
    "  --checkbox-snap-margin <int>  Pixel margin around the box when looking for\n"
    "                         the real rectangle (default: 4)\n"
    "  --checkbox-snap-min-area <f>  Minimum candidate area as a fraction of the\n"
    "                         search region (default: 0.07)\n"
    "  --checkbox-snap-max-area <f>  Maximum, likewise (default: 0.95)\n"
    "  --checkbox-snap-min-aspect <f>  Minimum accepted aspect (default: 0.4)\n"
    "  --checkbox-snap-max-aspect <f>  Maximum accepted aspect. Wide boxes exist\n"
    "                         (aspect ~2.4); 2.0 leaves them unsnapped\n"
    "                         (default: 3.0)\n"
    "  --checkbox-snap-rectangularity <f>  Minimum candidate rectangularity\n"
    "                         (default: 0.75)\n"
    "  --checkbox-ink-thresh <f>  Ink density above which a box counts as ticked.\n"
    "                         Measured: empty 0.000, typed X 0.08-0.17, dark fill\n"
    "                         0.60-0.91 (default: 0.05)\n"
    "  --checkbox-ink-border <f>  Fraction of the side cropped inwards to exclude\n"
    "                         the border (default: 0.25)\n"
    "  --checkbox-ink-dark <int>  Grey level below which a pixel counts as ink\n"
    "                         (default: 128)\n"
    "\n"
    "  Orphan bracket cleanup (off by default):\n"
    "  --clean-orphan-brackets [ratio]  Strip unmatched ()[]{} from OCR text\n"
    "                         per line (e.g. a cell border misread as \"[\" in\n"
    "                         \"Nombre[\"). Runs before any synthetic checkbox\n"
    "                         text exists, so \"[x]\"/\"[ ]\" are never touched.\n"
    "                         A pair spanning two lines is kept: if a bracket\n"
    "                         kind has both an unmatched open and an unmatched\n"
    "                         close on the page, none of that kind is removed.\n"
    "                         [ratio] is the code gate in the same flag: if the\n"
    "                         fraction of lines still holding an unmatched\n"
    "                         bracket exceeds it, the page is assumed to be\n"
    "                         scanned source code and the cleanup is skipped\n"
    "                         entirely for that page (default: 0.30)\n"
    "  --clean-brackets-gate-min-lines <int>  Minimum lines on the page for the\n"
    "                         gate above to apply; shorter pages are always\n"
    "                         cleaned (default: 5)\n"
    "  --clean-brackets-anywhere  Also remove unmatched brackets in the middle\n"
    "                         of a run, not just at its start/end. Higher\n"
    "                         recall, but it eats a legitimate \"(\" whose \")\"\n"
    "                         the OCR dropped (measured on a real form)\n"
    "\n"
    "  Diagnostics:\n"
    "  --debug-overlay <file> Write a copy of the page with the detected boxes\n"
    "                         drawn on it: checkboxes green (ticked) / red (empty)\n"
    "                         with their ink ratio and confidence, cells in blue.\n"
    "                         With several input images the page index is appended\n"
    "                         to the stem\n"
    "  --debug-checkbox-candidates  Also emit the discarded candidates in the JSON,\n"
    "                         each with the reason it was dropped (saturation,\n"
    "                         below-conf, rescue-pruned, nms)\n";

static const char *otherMsg =
    "  --version, -v           Print version and exit\n"
    "  --help, -h              Print this help and exit\n";

#endif //__PADDLEVINO_MAIN_H__
